export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const ADD_DATA_SUCCESS = "ADD_DATA_SUCCESS";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const CLEAR_DATA_SUCCESS = "CLEAR_DATA_SUCCESS";
export const EDIT_DATA_SUCCESS = "EDIT_DATA_SUCCESS";
